### ISSUE TITLE
Create symlinks instead of copying files

### ISSUE THREAD

**Issue by awskii** [lamartire/dotfiles#1]
https://github.com/lamartire/dotfiles/blob/9ccde603f40e3ec52ed4426c4059306403e2c6d8/servant#L39

Не претендую на грамотность решения, но у меня есть директория в корне, в которой лежат все дотфайлы и тп. 
Там же sh скрипт, который тупа делает симлинки в нужных местах на эти файлы. Соответственно в этой директории у меня всегда актуальные конфиги, и нужна только кронжоба, которая смотрит гит дифф и коммитит апдейт если дифф не пустой (кажется в этом случае git diff возвращает особый return code)

**Comment by epszaw** [comment]
Я честно говоря решил сделать максимально тупо – скопировал, да и пусть лежит. Но спасибо, попробую поиграться!
